// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: `tsx prisma/seed.ts`,
  },
  datasource: {
    // url: "mysql://root:11471347Fa%40@localhost:3306/nextapp",
    url: "mysql://2MWctRK3DnwzTpk.root:gpPXYNzHCEYYbB5H@gateway01.eu-central-1.prod.aws.tidbcloud.com:4000/test?sslaccept=strict",
  },
});
